name: trek10-teamdays-cloudfront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      STACK_NAME: trek10-team-days-cloudfront-broken-links
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci
        working-directory: elderjs-app
      - name: Build static content
        run: npm run-script build
        working-directory: elderjs-app

      - name: Deploy CloudFormation stack with broken links
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ${{ env.STACK_NAME }}
          template: template.yaml
          parameter-overrides: >-
            Domain=broken.charlieguse.com,
            EnableDefaultObjectForSubdirectories=Disabled
          no-fail-on-empty-changeset: 1

      - name: Publish static content to S3 Bucket
        run: $(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[*].Outputs[?OutputKey=='UploadCommand'].OutputValue" --output text)
